#!/bin/sh

function generate() {
echo "# Generated by inventory-generator.sh"
echo "[all_servers]"
for server in $(virsh -c qemu:///system list --all --name | sort); do
    ip=$(virsh -c qemu:///system domifaddr ${server} | grep -oE "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)")
    echo "${server} ansible_host=${ip}"
done

echo "
[k8s_cluster:children]
k8s_masters
k8s_workers

[etcd]
k8s-master01
k8s-master02
k8s-master03

[k8s_masters]
k8s-master01
k8s-master02
k8s-master03

[k8s_workers]
k8s-worker01
k8s-worker02
k8s-worker03

[haproxy]
haproxy01
haproxy02"
}

generate > $(dirname $0)/inventory.ini