---
- name: Create directory for CNI
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  loop:
    - /opt/cni/bin
    - /etc/cni/net.d

- name: Download CNI plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    dest: /tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    owner: root
    group: root
    mode: "0755"

- name: Install CNI plugins
  unarchive:
    src: /tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz
    dest: /opt/cni/bin
    remote_src: yes