---
# Création utilisateur
- include_tasks: 01-etcd-user.yml

# Téléchargement et installation
- include_tasks: 02-download-etcd.yml

# Génération des certificats SSL
- include_tasks: 03-certificats-generation.yml

# systemd et configuration
- include_tasks: 04-systemd+configuration.yml