---
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: /etc/kubernetes/kube-proxy.conf
mode: ipvs
ipvs:
  strictARP: true
clusterCIDR: {{ k8s_cluster_cidr }}