---
- name: Restart kube-apiserver
  service:
    name: kube-apiserver
    state: restarted

- name: Restart kube-scheduler
  service:
    name: kube-scheduler
    state: restarted

- name: Restart kube-controller-manager
  service:
    name: kube-controller-manager
    state: restarted

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Restart kube-proxy
  service:
    name: kube-proxy
    state: restarted