---
- name: Check if k8S if installed
  shell: test -x /usr/local/bin/kube-apiserver && /usr/local/bin/kube-apiserver --version | cut -d" " -f2 || exit 0
  register: check_k8s_version

- block:

  ## Binaries by binaries
  - name: Download k8s master binaries
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/{{ item }}
      dest: /usr/local/bin/{{ item }}
      owner: root
      group: root
      mode: "0755"
    loop:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - kubectl
      - kubeadm
    when: inventory_hostname in groups['k8s_masters']

  - name: Download k8s worker binaries
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/{{ item }}
      dest: /usr/local/bin/{{ item }}
      owner: root
      group: root
      mode: "0755"
    loop:
      - kubelet
      - kube-proxy
    when: inventory_hostname in groups['k8s_workers']

  when: check_k8s_version.stdout != k8s_version

- name: Create /etc/kubernetes directory
  file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: "0755"