---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-test
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-test
  template:
    metadata:
      labels:
        app: alpine-test
    spec:
      containers:
      - name: alpine-test
        image: alpine:3
        args:
        - sleep
        - "1000000"
        ports:
        - containerPort: 80
